spring:
    web-client:
        request:
            timeout: 120000
services:
    correios:
        url: ${CORREIOS_ENDPOINT}
    twilio:
        account-sid: ${ACCOUNT_SID}
        auth-token: ${AUTH_TOKEN}
        from: ${FROM}
